@startuml
left to right direction
skinparam packageStyle rectangle

skinparam actor {
  BackgroundColor<<Interne>> LightBlue
  BorderColor<<Interne>> Blue
  FontColor<<Interne>> Blue
}

actor "Client Géré" as clientGere
actor "Client Autonome" as clientAuto
actor "Service Commercial" as commercial <<Interne>>
actor "Service Livraisons" as livraisons <<Interne>>
actor "Administrateur" as admin <<Interne>>

rectangle "Application LiVrai" {

  together {
    usecase "S'inscrire" as UC1
    usecase "Se connecter" as UC2
    usecase "Gérer son profil" as UC3
  }

  together {
    usecase "Créer une demande de livraison" as UC4
    usecase "Suivre ses livraisons" as UC5
    usecase "Consulter ses factures" as UC6
  }

   usecase "Gérer les utilisateurs" as UC8

  together {
    usecase "Gérer les comptes clients" as UC7
    usecase "Établir les factures" as UC11
    usecase "Consulter les rapports financiers" as UC12
  }

  usecase "Traiter les demandes de livraison" as UC9
  usecase "Mettre à jour le statut des livraisons" as UC10

  ' Include relationships
  UC9 ..> UC10 : <<include>>
  UC7 ..> UC8 : <<include>>
  UC4 ..> UC2 : <<include>>
  UC5 ..> UC2 : <<include>>
  UC6 ..> UC2 : <<include>>

  ' Extend relationships
  UC11 ..> UC9 : <<extend>>
}

clientAuto <|-- clientGere
clientAuto --> UC1
clientGere --> UC2
clientGere --> UC3
clientGere --> UC4
clientGere --> UC5
clientGere --> UC6
admin --> UC8

UC2 <-- commercial
UC3 <-- commercial
UC7 <-- commercial
UC8 <-- commercial
UC12 <-- commercial
UC11 <-- commercial

UC9 <-- livraisons
UC10 <-- livraisons

commercial -right-> UC2

@enduml
